description: >
  Sample example description.
# Provide a use-case based example for using this orb.
# Everything in the `usage` section will be displayed in the orb registry.
# Comments are not retained.
usage:
  version: 2.1
  orbs:
      macos: circleci/macos@1.0
  jobs:
    build-test:
      macos:
        xcode: 11.7
      steps:
          - checkout
          - run: echo 'chruby ruby-2.7' >> ~/.bash_profile
          - macos/add-mac-uitest-permissions
          - run: bundle install
          - run: bundle exec fastlane testandbuild
  workflows:
      verify:
          jobs:
              - build-test