description: >
  Sample example description.
# Provide a use-case based example for using this orb.
# Everything in the `usage` section will be displayed in the orb registry.
# Comments are not retained.
usage:
  version: 2.1
  orbs:
    macos: circleci/macos@1.0
  jobs:
    test-macos-app:
      macos:
        xcode: 12.0.0
      steps:
        - checkout
        - macos/add-uitest-permissions
        - run: echo 'Test my app'
  workflows:
    test-deploy:
      jobs:
        - test-macos-app
        - deploy:
            requires:
              - test-macos-app
            filter:
              branches:
                only:
                  - production
